app/db/models/position.py
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy import String

from app.db import Base


class Position(Base):
    __tablename__ = "positions"

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(50))

app/db/models/post.py
from datetime import datetime

from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy import String, TEXT, ForeignKey
from sqlalchemy.types import TIMESTAMP
from sqlalchemy.sql import func

from app.db import Base, User


class Post(Base):
    __tablename__ = "posts"

    id: Mapped[int] = mapped_column(primary_key=True)
    title: Mapped[str] = mapped_column(String(500))
    text: Mapped[str] = mapped_column(TEXT())
    create: Mapped[datetime] = mapped_column(TIMESTAMP(), server_default=func.now())
    user_id: Mapped[int] = mapped_column(ForeignKey(User.id))
    user: Mapped[User] = relationship()

app/db/models/user.py
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy import String, ForeignKey

from app.db import Base, Position


class User(Base):
    __tablename__ = "users"

    id: Mapped[int] = mapped_column(primary_key=True)
    first_name: Mapped[str] = mapped_column(String(50), nullable=True)
    last_name: Mapped[int] = mapped_column(String(50))
    age: Mapped[int] = mapped_column(nullable=True)
    position_id: Mapped[int] = mapped_column(ForeignKey(Position.id))
    position: Mapped[Position] = relationship()

app/__init__.py
from flask import Flask

from app.db import create_db
from app.routes import position_route, user_route, post_route
from app.data.password import ADMIN_PASS


app = Flask(__name__)
app.secret_key = ADMIN_PASS
app.register_blueprint(position_route)
app.register_blueprint(user_route)
app.register_blueprint(post_route)


def main():
    create_db()
    app.run(debug=True)

app/db/__init__.py
from .base import Base, Session, create_db
from .models.position import Position
from .models.user import User
from .models.post import Post

app/routes/__init__.py
from .position import position_route
from .user import user_route
from .post import post_route

app/routes/position.py
from flask import Blueprint, render_template, request, redirect

from app.db import Session, Position
from app.data.password import ADMIN_PASS

position_route = Blueprint("positions", __name__, url_prefix="/positions/")


@position_route.get("/")
@position_route.post("/")
def add_position():
    msg = ""
    block = False
    with Session() as session:
        if request.method == "POST":
            name = request.form.get("name")
            password = request.form.get("password")

            if password == ADMIN_PASS:
                position = Position(name=name)
                session.add(position)
                session.commit()
                msg = "Нова посада успішно додана"
            else:
                block = True

    return render_template("add_position.html", msg=msg, block=block)

app/routes/post.py
from flask import Blueprint, render_template, request, redirect, url_for, flash

from app.db import Session, User, Post
from app.data.password import ADMIN_PASS


post_route = Blueprint("posts", __name__)


@post_route.get("/posts/")
@post_route.post("/posts/")
def add_post():
    with Session() as session:
        if request.method == "POST":
            title = request.form.get("title")
            text = request.form.get("text")
            user_id = request.form.get("user_id")

            if request.form.get("password") == ADMIN_PASS:
                post = Post(title=title, text=text, user_id=user_id)
                session.add(post)
                session.commit()
                flash("Статтю успішно додано")
            else:
                flash("Не вірний пароль. Доступ заблоковано")

        users = session.query(User).all()
        return render_template("add_post.html", users=users)


@post_route.get("/")
def index():
    with Session() as session:
        posts = session.query(Post).all()
        return render_template("index.html", posts=posts)


@post_route.get("/post/<int:id>")
def get_post(id):
    with Session() as session:
        post = session.query(Post).where(Post.id == id).first()
        return render_template("post.html", post=post)


@post_route.get("/post/delete/<int:id>/")
def del_post(id):
    with Session() as session:
        post = session.query(Post).where(Post.id == id).first()
        session.delete(post)
        session.commit()

    return redirect(url_for("posts.index"))


@post_route.get("/post/edit/<int:id>/")
@post_route.post("/post/edit/<int:id>/")
def edit_post(id):
    with Session() as session:
        post = session.query(Post).where(Post.id == id).first()

        if request.method == "POST":
            post.title = request.form.get("title")
            post.text = request.form.get("text")
            session.commit()
            return redirect(url_for("posts.get_post", id=id))

        return render_template("add_post.html", post=post)

app/routes/user.py
from flask import Blueprint, render_template, request

from app.db import Session, User, Position
from app.data.password import ADMIN_PASS

user_route = Blueprint("users", __name__, url_prefix="/users/")


@user_route.get("/")
@user_route.post("/")
def add_user():
    msg = ""
    block = False

    with Session() as session:
        if request.method == "POST":
            first_name = request.form.get("first_name")
            last_name = request.form.get("last_name")
            age = request.form.get("age")
            position_id = request.form.get("position_id")
            user = User(first_name=first_name, last_name=last_name, age=age, position_id=position_id)

            if request.form.get("password") == ADMIN_PASS:
                session.add(user)
                session.commit()
                msg = "Користувача успішно додано"
            else:
                block = True

        positions = session.query(Position).all()
        context = {
            "msg": msg,
            "block": block,
            "positions": positions
        }

        return render_template("add_user.html", **context)

app/templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <title>{% block title %} FlaskBlog {% endblock title %}</title>
</head>
<body class="p-5 bg-primary-subtle">
    {% include "_navbar.html" %}

    {% block content %}
    {% endblock content %}
    <div class="container text-center">
        <div class="row">
            <div class="col">
                {% block left_content %}
                {% endblock left_content %}
            </div>
            <div class="col">
                {% block center_content %}
                {% endblock center_content %}
            </div>
            <div class="col">
                {% block right_content %}
                {% endblock right_content %}
            </div>
        </div>
    </div>
</body>
</html>

app/templates/_navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('posts.index') }}">Головна сторінка</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{ url_for('posts.add_post') }}">Додати статтю</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{ url_for('users.add_user') }}">Додати користувача</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{ url_for('positions.add_position') }}">Додати посаду</a>
        </li>
    </div>
  </div>
</nav>

app/templates/add_position.html
{% extends "_base.html" %}

{% block center_content %}
<form action="{{ url_for('positions.add_position') }}" method="post">
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Назва посади</label>
    <input type="text" class="form-control" name="name">
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Пароль адміністратора</label>
    <input type="password" class="form-control" id="exampleInputPassword1" name="password">
  </div>
  <button type="submit" class="btn btn-primary">Додати</button>
  <div id="emailHelp" class="form-text">{{ msg }}</div>
</form>

{% if block %}
  <img src="https://http.cat/401" height="300" width="400">
{% endif %}

{% endblock center_content %}

app/templates/add_post.html
{% extends "_base.html" %}

{% block center_content %}

{% if post %}
  <form action="{{ url_for('posts.edit_post', id=post.id) }}" method="post">
{% else %}
 <form action="{{ url_for('posts.add_post') }}" method="post">
{% endif %}

  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Назва статті</label>

    {% if post %}
      <input type="text" class="form-control" name="title" value="{{ request.form.title or post.title }}">
    {% else %}
      <input type="text" class="form-control" name="title" value="{{ request.form.title }}">
    {% endif %}

  </div>
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Текст</label>

    {% if post %}
      <textarea class="form-control" name="text">{{ request.form.text or post.text }}</textarea>
    {% else %}
      <textarea class="form-control" name="text">{{ request.form.text }}</textarea>
    {% endif %}

  </div>

  {% if post %}
    <input type="text" name="user_id" value="{{ post.user_id }}" hidden>
  {% else %}
    <select name="user_id">
      {% for user in users %}
          <label>Виберіть користувача</label>
          <option value="{{ user.id }}">{{ user.last_name }} {{ user.first_name }}</option>
      {% endfor %}
    </select>
  {% endif %}

  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Пароль адміністратора</label>
    <input type="password" class="form-control" id="exampleInputPassword1" name="password">
  </div>
  <button type="submit" class="btn btn-primary">{% if post %} Редагувати статтю {% else %} Додати {% endif %}</button>

  {% with messages = get_flashed_messages() %}
    {% for message in messages %}
      <div id="emailHelp" class="form-text">{{ message }}</div>
    {% endfor %}
  {% endwith %}

</form>
{% endblock center_content %}

app/templates/add_user.html
{% extends "_base.html" %}

{% block center_content %}
<form action="{{ url_for('users.add_user') }}" method="post">
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Ім'я</label>
    <input type="text" class="form-control" name="first_name">
  </div>
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Прізвище</label>
    <input type="text" class="form-control" name="last_name">
  </div>
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Вік</label>
    <input type="number" class="form-control" name="age">
  </div>
  <select name="position_id">
    {% for position in positions %}
        <label>Виберіть посаду</label>
        <option value="{{ position.id }}">{{ position.name }}</option>
    {% endfor %}
  </select>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Пароль адміністратора</label>
    <input type="password" class="form-control" id="exampleInputPassword1" name="password">
  </div>
  <button type="submit" class="btn btn-primary">Додати</button>
  <div id="emailHelp" class="form-text">{{ msg }}</div>
</form>

{% if block %}
  <img src="https://http.cat/401" height="300" width="400">
{% endif %}

{% endblock center_content %}

app/templates/index.html
{% extends "_base.html" %}


{% block center_content %}
    {% for post in posts %}
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">{{ post.title }}</h5>
            <p class="card-text">Автор: <em>{{ post.user.last_name }} {{ post.user.first_name }}</em></p>
            <h5><p>{{ post.create }}</p></h5>
            <a href="{{ url_for('posts.get_post', id=post.id) }}" class="btn btn-primary">Відкрити статтю</a>
        </div>
    </div>
    {% endfor %}
{% endblock center_content %}

app/templates/post.html
{% extends "_base.html" %}


{% block content %}
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">{{ post.title }}</h5>
            <p class="card-text">{{ post.text }}</p>
        </div>
    </div>
    <a href="{{ url_for('posts.edit_post', id=post.id) }}" class="btn btn-info">Редагувати статтю</a>
    <a href="{{ url_for('posts.del_post', id=post.id) }}" class="btn btn-danger">Видалити статтю</a>
{% endblock content %}